"""
model_insights_page.py — Global model performance and feature importance page.

This page gives a dataset-level view of the model rather than a per-applicant view.
It shows three sections:
  1. Model Comparison — accuracy and ROC-AUC scores from cross-validation,
     loaded from a CSV generated during training.
  2. Dataset Summary — class distribution (approved vs rejected) and the list
     of numeric and categorical feature columns.
  3. Global SHAP Summary — which features had the greatest overall influence
     on the model's predictions, shown as a table and optionally as a beeswarm
     plot image if one was saved during training.

This page does not show per-applicant data. For individual explanations,
the user should navigate to the Loan Decision page.
"""
import os
import pandas as pd
import streamlit as st


def render_model_insights_page(
    model_df,
    get_model_comparison_df,
    get_top_global_features_df,
    global_shap_image,
):
    """
    Render the Model Insights page.

    Parameters:
        model_df               : Model-ready DataFrame, used only for the dataset summary section.
        get_model_comparison_df: Callable returning a DataFrame of cross-validation results
                                 (loaded from outputs/model_performance_cv.csv if it exists).
        get_top_global_features_df: Callable computing mean |SHAP| per feature across all applicants.
        global_shap_image      : Filesystem path to the global SHAP beeswarm plot PNG,
                                 generated during training. The image is shown only if the
                                 file exists; otherwise a fallback message is displayed.
    """
    st.title("📊 Model Insights")
    st.write("Overview of model performance, data profile, and global feature importance.")

    # ── Model Comparison ───────────────────────────────────────────────────
    # The comparison CSV is generated by train.py after evaluating multiple
    # classifiers. Column names are checked defensively because the CSV schema
    # can vary depending on which training script version produced the file.
    comparison_df = get_model_comparison_df()

    st.subheader("Model Comparison")

    if comparison_df is None or comparison_df.empty:
        st.warning("Model comparison results not found. Run train.py first.")
    else:
        columns = comparison_df.columns
        model_col = "Model_Name" if "Model_Name" in columns else "Model"
        auc_col = "CV_Mean_ROC_AUC" if "CV_Mean_ROC_AUC" in columns else "ROC_AUC"
        acc_col = "Accuracy" if "Accuracy" in columns else columns[2]

        sorted_df = comparison_df.sort_values(by=auc_col, ascending=False)
        best_model = sorted_df.iloc[0]

        col1, col2, col3 = st.columns(3)
        col1.metric("Best Model", str(best_model[model_col]).replace("_", " "))
        col2.metric("Best Accuracy", f"{float(best_model[acc_col]):.2%}")
        col3.metric("Best ROC-AUC", f"{float(best_model[auc_col]):.4f}")

        st.dataframe(comparison_df, use_container_width=True, hide_index=True)

    st.subheader("Dataset Summary")

    target_counts = model_df["Loan_Status"].value_counts().rename(
        index={1: "Approved", 0: "Rejected"}
    )

    target_percent = (
        model_df["Loan_Status"].value_counts(normalize=True) * 100
    ).rename(
        index={1: "Approved", 0: "Rejected"}
    )

    summary_col1, summary_col2 = st.columns(2)

    with summary_col1:
        st.write("Target Distribution")
        target_summary = pd.DataFrame(
            {
                "Count": target_counts,
                "Percentage": target_percent.round(2).astype(str) + "%",
            }
        )
        st.dataframe(target_summary, use_container_width=True)

    with summary_col2:
        feature_df = model_df.drop(columns=["Loan_Status"])
        categorical_cols = feature_df.select_dtypes(
            include=["object", "category"]
        ).columns.tolist()
        numeric_cols = feature_df.select_dtypes(
            include=["int64", "float64"]
        ).columns.tolist()

        st.write("Feature Groups")
        st.info(f"Numeric columns ({len(numeric_cols)}): {', '.join(numeric_cols)}")
        st.info(f"Categorical columns ({len(categorical_cols)}): {', '.join(categorical_cols)}")

    # ── Global Feature Importance ──────────────────────────────────────────
    # get_top_global_features_df() calls calculate_global_shap_importance(),
    # which runs SHAP on the entire dataset and takes several seconds on first
    # call. The result is cached in explainability.py via @st.cache_data.
    st.subheader("Top Global Features")
    try:
        global_features_df = get_top_global_features_df()
        if global_features_df is not None and not global_features_df.empty:
            st.dataframe(global_features_df, use_container_width=True, hide_index=True)
        else:
            st.caption("Global feature importance rank metrics empty.")
    except Exception as e:
        st.caption(f"Global weights tracking unavailable: {e}")

    if os.path.exists(global_shap_image):
        st.subheader("Global SHAP Summary Plot")
        # The explanation sits beside the chart so reviewers can read the guidance
        # while looking at the SHAP summary plot without scrolling up and down.
        shap_left, shap_right = st.columns([1, 2.2])
        with shap_left:
            with st.expander("How to read this chart", expanded=True):
                st.markdown(
                    "This chart summarises feature importance **across all applicants in the dataset**, "
                    "not just one individual. Features listed at the top had the greatest overall "
                    "influence on the model's predictions.\n\n"
                    "Each dot represents one applicant. The colour indicates the feature value "
                    "(red = high value, blue = low value). The horizontal position shows whether "
                    "that value pushed the prediction toward approval (right) or rejection (left).\n\n"
                    "This is a **global** view of model behaviour. To see how a specific applicant's "
                    "profile was evaluated, open the **Loan Decision** page and scroll to the "
                    "*Why This Decision?* section — that chart explains a single applicant's prediction."
                )
        with shap_right:
            st.image(global_shap_image, caption="Global SHAP feature importance")
    else:
        st.info("Global SHAP summary image not found. Run your explainability script first.")