"""
model_insights_page.py — Global model performance and feature importance page.

This page gives a dataset-level view of the model rather than a per-applicant view.
It shows three sections:
  1. Model Comparison — accuracy and ROC-AUC scores from cross-validation,
     loaded from a CSV generated during training.
  2. Dataset Summary — class distribution (approved vs rejected) and the list
     of numeric and categorical feature columns.
  3. Global SHAP Summary — which features had the greatest overall influence
     on the model's predictions, shown as a table and optionally as a beeswarm
     plot image if one was saved during training.

This page does not show per-applicant data. For individual explanations,
the user should navigate to the Loan Decision page.
"""
import os
from pathlib import Path

import pandas as pd
import streamlit as st

from config import OUTPUT_DIR


def render_model_insights_page(
    model_df,
    get_model_comparison_df,
    get_top_global_features_df,
    global_shap_image,
):
    """
    Render the Model Insights page.

    Parameters:
        model_df               : Model-ready DataFrame, used only for the dataset summary section.
        get_model_comparison_df: Callable returning a DataFrame of cross-validation results
                                 (loaded from outputs/model_performance_cv.csv if it exists).
        get_top_global_features_df: Callable computing mean |SHAP| per feature across all applicants.
        global_shap_image      : Filesystem path to the global SHAP beeswarm plot PNG,
                                 generated during training. The image is shown only if the
                                 file exists; otherwise a fallback message is displayed.
    """
    st.title("📊 Model Insights")
    st.write("Overview of model performance, data profile, and global feature importance.")

    # ── Model Comparison ───────────────────────────────────────────────────
    # The comparison CSV is generated by train.py after evaluating multiple
    # classifiers. Column names are checked defensively because the CSV schema
    # can vary depending on which training script version produced the file.
    comparison_df = get_model_comparison_df()

    st.subheader("Model Comparison")

    if comparison_df is None or comparison_df.empty:
        st.warning("Model comparison results not found. Run train.py first.")
    else:
        columns = comparison_df.columns.tolist()

        model_col = "Model_Name" if "Model_Name" in columns else "Model"

        if "CV_Mean_ROC_AUC" in columns:
            auc_col = "CV_Mean_ROC_AUC"
        elif "ROC_AUC" in columns:
            auc_col = "ROC_AUC"
        elif "AUC" in columns:
            auc_col = "AUC"
        else:
            auc_col = None

        if "Accuracy" in columns:
            acc_col = "Accuracy"
        elif auc_col is not None:
            acc_col = auc_col
        else:
            numeric_cols = comparison_df.select_dtypes(include="number").columns.tolist()
            acc_col = numeric_cols[0] if numeric_cols else None

        if auc_col is None and acc_col is None:
            st.warning(
                "No accuracy or ranking score (ROC-AUC) column was found in the model comparison data. "
                f"Available columns: {', '.join(columns)}"
            )
            st.dataframe(comparison_df, use_container_width=True, hide_index=True)
        else:
            sort_col = auc_col if auc_col is not None else acc_col
            sorted_df = comparison_df.sort_values(by=sort_col, ascending=False)
            best_model = sorted_df.iloc[0]

            col1, col2, col3 = st.columns(3)
            col1.metric("Best Model", str(best_model[model_col]).replace("_", " "))
            if acc_col is not None:
                col2.metric("Best Accuracy", f"{float(best_model[acc_col]):.2%}")
            else:
                col2.empty()
            if auc_col is not None:
                col3.metric("Best Ranking Score (ROC-AUC)", f"{float(best_model[auc_col]):.4f}")
            else:
                col3.empty()

            st.dataframe(comparison_df, use_container_width=True, hide_index=True)

    # ── Fairness Metrics ───────────────────────────────────────────────────
    # The fairness metrics are generated during training, so the dashboard
    # checks whether the CSV exists before trying to display it.
    st.subheader("Fairness Metrics")
    st.write(
        "Fairness metrics show whether the model behaves differently across applicant groups. "
        "Smaller differences are generally better because they suggest the model is more "
        "consistent across groups. These metrics are intended for monitoring and review, "
        "not as a final legal or regulatory judgement."
    )

    with st.expander("How to read these fairness metrics"):
        st.markdown(
            "**Demographic Parity Difference:** compares approval rates between groups. "
            "Lower is better. A value of 0 means the model approves loans at the same rate "
            "for all groups.\n\n"
            "**Equal Opportunity Difference:** compares correct approval rates between groups "
            "(i.e. how often qualified applicants are approved). Lower is better. A value of 0 "
            "means qualified applicants are equally likely to be approved regardless of group.\n\n"
            "**Disparate Impact Ratio** (where shown): compares approval rates between groups "
            "as a ratio. Values closer to 1.0 are generally better. A value below 0.8 is often "
            "flagged as a concern in fairness guidelines."
        )

    _fairness_path = Path(OUTPUT_DIR) / "fairness_metrics.csv"
    _audit_path = Path(OUTPUT_DIR) / "fairness_audit_report.csv"

    if not _fairness_path.exists():
        st.warning(
            "Fairness metrics file not found. Run train.py to generate fairness_metrics.csv."
        )
    else:
        import plotly.graph_objects as go

        fairness_df = pd.read_csv(_fairness_path)

        # ── Model selector ─────────────────────────────────────────────────
        model_col = "Model" if "Model" in fairness_df.columns else (
            "Model_Name" if "Model_Name" in fairness_df.columns else None
        )

        if model_col is not None and fairness_df[model_col].nunique() > 1:
            available_models = fairness_df[model_col].unique().tolist()
            default_model = (
                "Logistic Regression"
                if "Logistic Regression" in available_models
                else available_models[0]
            )
            selected_model = st.selectbox(
                "Select model for fairness view",
                options=available_models,
                index=available_models.index(default_model),
            )
        else:
            selected_model = (
                fairness_df[model_col].iloc[0] if model_col is not None else None
            )

        model_fairness_df = (
            fairness_df[fairness_df[model_col] == selected_model].copy()
            if model_col is not None
            else fairness_df.copy()
        )

        # ── Fairness gap chart ─────────────────────────────────────────────
        feat_col = (
            "Sensitive_Feature"
            if "Sensitive_Feature" in model_fairness_df.columns
            else None
        )
        dpd_col = next(
            (c for c in ["Demographic_Parity_Difference", "Demographic_Parity_Diff"]
             if c in model_fairness_df.columns),
            None,
        )
        eod_col = next(
            (c for c in ["Equal_Opportunity_Difference", "Equal_Opportunity_Diff"]
             if c in model_fairness_df.columns),
            None,
        )

        if feat_col and (dpd_col or eod_col):
            fig = go.Figure()

            if dpd_col:
                fig.add_trace(go.Bar(
                    name="Demographic Parity Difference",
                    x=model_fairness_df[feat_col],
                    y=model_fairness_df[dpd_col].abs(),
                    marker_color="#4C78A8",
                ))
            if eod_col:
                fig.add_trace(go.Bar(
                    name="Equal Opportunity Difference",
                    x=model_fairness_df[feat_col],
                    y=model_fairness_df[eod_col].abs(),
                    marker_color="#F58518",
                ))

            # Reference lines at fairness gap thresholds
            fig.add_hline(
                y=0.05, line_dash="dot", line_color="green",
                annotation_text="Low/Medium threshold (0.05)",
                annotation_position="top right",
            )
            fig.add_hline(
                y=0.15, line_dash="dot", line_color="red",
                annotation_text="Medium/High threshold (0.15)",
                annotation_position="top right",
            )

            fig.update_layout(
                barmode="group",
                title=f"Fairness Gaps by Sensitive Feature: {selected_model}",
                xaxis_title="Sensitive Feature",
                yaxis_title="Fairness Gap (absolute value)",
                legend_title="Metric",
                yaxis_range=[0, max(
                    model_fairness_df[dpd_col].abs().max() if dpd_col else 0,
                    model_fairness_df[eod_col].abs().max() if eod_col else 0,
                    0.20,
                ) * 1.15],
                height=400,
            )
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.warning("Could not render fairness chart: expected columns not found.")

        # ── Risk-label table ───────────────────────────────────────────────
        def _gap_label(val):
            try:
                v = abs(float(val))
            except (TypeError, ValueError):
                return "—"
            if v < 0.05:
                return "Low gap"
            if v < 0.15:
                return "Medium gap"
            return "High gap"

        display_df = model_fairness_df.copy()
        numeric_display_cols = display_df.select_dtypes(include="number").columns
        display_df[numeric_display_cols] = display_df[numeric_display_cols].round(3)

        if dpd_col:
            display_df["Demographic Parity Level"] = model_fairness_df[dpd_col].apply(_gap_label)
        if eod_col:
            display_df["Equal Opportunity Level"] = model_fairness_df[eod_col].apply(_gap_label)

        # Drop raw group-rate columns from the summary table (shown separately below)
        summary_cols = [
            c for c in display_df.columns
            if c not in ("Approval_Rates_By_Group", "Recall_Rates_By_Group")
        ]
        st.dataframe(display_df[summary_cols], use_container_width=True, hide_index=True)

        # ── Full detailed table ────────────────────────────────────────────
        full_display = fairness_df.copy()
        full_numeric = full_display.select_dtypes(include="number").columns
        full_display[full_numeric] = full_display[full_numeric].round(3)
        with st.expander("Show full fairness metrics table (all models)"):
            st.dataframe(full_display, use_container_width=True, hide_index=True)

        # ── Detailed group rates ───────────────────────────────────────────
        has_group_cols = (
            "Approval_Rates_By_Group" in model_fairness_df.columns
            or "Recall_Rates_By_Group" in model_fairness_df.columns
        )
        audit_exists = _audit_path.exists()

        if has_group_cols or audit_exists:
            with st.expander("Detailed group rates"):
                st.caption(
                    "These tables show approval and recall rates broken down by group within "
                    "each sensitive feature. This is more technical detail for reviewers who "
                    "want to see the underlying numbers behind the fairness gaps above."
                )
                if has_group_cols and feat_col:
                    for _, row in model_fairness_df.iterrows():
                        feature_label = row.get(feat_col, "")
                        st.markdown(f"**{feature_label}**")
                        rate_rows = []
                        for rate_col, label in [
                            ("Approval_Rates_By_Group", "Approval Rate"),
                            ("Recall_Rates_By_Group", "Recall Rate"),
                        ]:
                            if rate_col in row and pd.notna(row[rate_col]):
                                try:
                                    rates = eval(str(row[rate_col]))  # noqa: S307 — trusted CSV output
                                    for group, val in rates.items():
                                        rate_rows.append({
                                            "Group": group,
                                            label: f"{val:.1%}",
                                        })
                                except Exception:
                                    pass
                        if rate_rows:
                            rates_display = pd.DataFrame(rate_rows)
                            if len(rates_display.columns) > 2:
                                # merge approval + recall into one table per feature
                                rates_display = (
                                    rates_display.groupby("Group")
                                    .first()
                                    .reset_index()
                                )
                            st.dataframe(rates_display, use_container_width=True, hide_index=True)

                if audit_exists:
                    audit_df = pd.read_csv(_audit_path)
                    audit_numeric = audit_df.select_dtypes(include="number").columns
                    audit_df[audit_numeric] = audit_df[audit_numeric].round(4)
                    st.markdown("**Overall audit summary (all models)**")
                    st.dataframe(audit_df, use_container_width=True, hide_index=True)

    st.subheader("Dataset Summary")

    target_counts = model_df["Loan_Status"].value_counts().rename(
        index={1: "Approved", 0: "Rejected"}
    )

    target_percent = (
        model_df["Loan_Status"].value_counts(normalize=True) * 100
    ).rename(
        index={1: "Approved", 0: "Rejected"}
    )

    summary_col1, summary_col2 = st.columns(2)

    with summary_col1:
        st.write("Target Distribution")
        target_summary = pd.DataFrame(
            {
                "Count": target_counts,
                "Percentage": target_percent.round(2).astype(str) + "%",
            }
        )
        st.dataframe(target_summary, use_container_width=True)

    with summary_col2:
        feature_df = model_df.drop(columns=["Loan_Status"])
        categorical_cols = feature_df.select_dtypes(
            include=["object", "category"]
        ).columns.tolist()
        numeric_cols = feature_df.select_dtypes(
            include=["int64", "float64"]
        ).columns.tolist()

        st.write("Feature Groups")
        st.info(f"Numeric columns ({len(numeric_cols)}): {', '.join(numeric_cols)}")
        st.info(f"Categorical columns ({len(categorical_cols)}): {', '.join(categorical_cols)}")

    # ── Global Feature Importance ──────────────────────────────────────────
    # get_top_global_features_df() calls calculate_global_shap_importance(),
    # which runs SHAP on the entire dataset and takes several seconds on first
    # call. The result is cached in explainability.py via @st.cache_data.
    st.subheader("Top Global Features")
    try:
        global_features_df = get_top_global_features_df()
        if global_features_df is not None and not global_features_df.empty:
            st.dataframe(global_features_df, use_container_width=True, hide_index=True)
        else:
            st.caption("Global feature importance rank metrics empty.")
    except Exception as e:
        st.caption(f"Global weights tracking unavailable: {e}")

    if os.path.exists(global_shap_image):
        st.subheader("Global Feature Importance Summary")
        # The explanation sits beside the chart so reviewers can read the guidance
        # while looking at the SHAP summary plot without scrolling up and down.
        shap_left, shap_right = st.columns([1, 2.2])
        with shap_left:
            with st.expander("How to read this chart", expanded=True):
                st.markdown(
                    "This chart summarises feature importance **across all applicants in the dataset**, "
                    "not just one individual. Features listed at the top had the greatest overall "
                    "influence on the model's predictions.\n\n"
                    "Each dot represents one applicant. The colour indicates the feature value "
                    "(red = high value, blue = low value). The horizontal position shows whether "
                    "that value pushed the prediction toward approval (right) or rejection (left).\n\n"
                    "This is a **global** view of model behaviour. To see how a specific applicant's "
                    "profile was evaluated, open the **Loan Decision** page and scroll to the "
                    "*Why This Decision?* section. That chart explains a single applicant's prediction."
                )
        with shap_right:
            st.image(global_shap_image, caption="Overall feature importance across all applicants")
    else:
        st.info("Global SHAP summary image not found. Run your explainability script first.")